name: CI/CD Pipline

on:
    push:
        branches:
            - dev
            - main
    pull_request:
        branches:
            - main
jobs:
    test:
        name: Run Test
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/setup-python@v4

              with:
                python-version: "3.11.4"
            - name: Install Dependencies
              run: pip install -r requirements.txt

            - name: Run Tests
              run: pytest --maxfail=5 --disable-warnings -v

    build-and-push:

        name: Build & Push Docker Image
        runs-on: ubuntu-latest
        needs: test #Runs only if tests pass

        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Log in Docker Hub
              if: github.ref == 'refs/heads/dev'
              uses: docker/login-action@v2
              with:
                username: ${{secrets.DOCKER_USERNAME}}
                password: ${{secrets.DOCKER_PASSWORD}}

            - name: Build Docker Image
              run: docker build -t ${{ secrets.DOCKER_USERNAME }}/sentiment-api:latest .

            - name: Push Docker Image (Only on Dev)
              if: github.ref == 'refs/heads/dev'
              run:  docker push ${{ secrets.DOCKER_USERNAME }}/sentiment-api:latest
    deploy-to-render:
        name: Deploy to Render (Production)
        runs-on: ubuntu-latest
        needs: test #Ensure tests pass first
        if: github.ref == 'refs/heads/main' #Only deploy if pushing to main

        steps:
            - name: Trigger Render Deployment
              run: |
                    curl -X POST "https://api.render.com/deploy/${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}
